// Code generated by tools/codegen from schemas/. DO NOT EDIT.
//
// The JSON Schemas in schemas/ are the source of truth; these types are one
// projection of them. Editing this file makes it the second definition of a
// primitive, which is the thing schemas/README.md exists to prevent.
//
// What is NOT here: every constraint a Go type cannot carry — minLength,
// patterns, enum membership on input, conditional requirements. Those are
// enforced by validating against the schema itself (pkg/schema.Validate), not
// by the struct. A value of one of these types is well-shaped, not valid.
package schema

import "time"

// Party X may exercise functions F, in scope G, for period T, per
// authority A — evidenced, approved, never transferable. One object at
// two scopes: instance-wide, and context-bound as a strict subset of an
// instance one.
type Authorization struct {
	ApprovedAt        time.Time `json:"approvedAt"`
	ApprovedByPartyID string    `json:"approvedByPartyId"`

	// Who says so. A verifier walks this.
	AuthorityPartyID string                      `json:"authorityPartyId"`
	Evidence         []AuthorizationEvidenceItem `json:"evidence,omitempty"`
	Functions        []string                    `json:"functions"`
	ID               string                      `json:"id"`
	PartyID          string                      `json:"partyId"`
	Period           Period                      `json:"period"`
	RevokedAt        *time.Time                  `json:"revokedAt,omitempty"`
	Scope            AuthorizationScope          `json:"scope"`
	State            AuthorizationState          `json:"state"`
	Terms            VersionedRef                `json:"terms"`
}

type AuthorizationEvidenceItem struct {
	Kind string `json:"kind"`
	Ref  string `json:"ref"`
}

type AuthorizationScope struct {
	ContextID *string                `json:"contextId,omitempty"`
	Kind      AuthorizationScopeKind `json:"kind"`
}

type AuthorizationScopeKind string

const (
	AuthorizationScopeKindInstance AuthorizationScopeKind = "instance"
	AuthorizationScopeKindContext  AuthorizationScopeKind = "context"
)

type AuthorizationState string

const (
	AuthorizationStateACTIVE  AuthorizationState = "ACTIVE"
	AuthorizationStateREVOKED AuthorizationState = "REVOKED"
	AuthorizationStateEXPIRED AuthorizationState = "EXPIRED"
)

// The L1 artefact every class adapter must emit (§8). CREST absorbs
// heterogeneity; source systems change nothing. A record providing only
// the mandatory core is valid Tier-1-capable evidence.
type CanonicalWorkEvidenceRecord struct {

	// Matched against a Definition's activity code by the evidence
	// pipeline.
	Activity string `json:"activity"`

	// Beneficiary counts, session metadata, supervisor identity, device
	// attestation. Optional, kept verbatim, read only by a definition's
	// tier map.
	Enrichment map[string]any `json:"enrichment,omitempty"`

	// Coarse only. A raw GPS fix is a rejection, not a truncation.
	Geography  *string    `json:"geography,omitempty"`
	Outcome    Outcome    `json:"outcome"`
	Period     Period     `json:"period"`
	Provenance Provenance `json:"provenance"`

	// Whatever joining identifier the source has. Resolved to a Party by
	// the matching rules (§4.1); no match means the unclear queue, never
	// a silent guess.
	WorkerJoiningIdentifier CanonicalWorkEvidenceRecordWorkerJoiningIdentifier `json:"workerJoiningIdentifier"`
}

// Whatever joining identifier the source has. Resolved to a Party by the
// matching rules (§4.1); no match means the unclear queue, never a silent
// guess.
type CanonicalWorkEvidenceRecordWorkerJoiningIdentifier struct {
	Kind CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKind `json:"kind"`

	// For kind=national-id this is the raw number in transit only. It is
	// resolved at ingestion and discarded — never persisted, not even in
	// fixtures (W9).
	Value string `json:"value"`
}

type CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKind string

const (
	CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKindNationalID CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKind = "national-id"
	CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKindPhone      CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKind = "phone"
	CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKindRosterID   CanonicalWorkEvidenceRecordWorkerJoiningIdentifierKind = "roster-id"
)

// How the fact was captured at source.
type CaptureMethod string

const (
	CaptureMethodSystemOfRecord     CaptureMethod = "system-of-record"
	CaptureMethodDigitalCapture     CaptureMethod = "digital-capture"
	CaptureMethodSupervisedManual   CaptureMethod = "supervised-manual"
	CaptureMethodUnsupervisedManual CaptureMethod = "unsupervised-manual"
)

// Party P performed (part of) Unit U — zero, one or many per unit. The
// only place actor and activity meet.
type Claim struct {
	Confirmation *ClaimConfirmation `json:"confirmation,omitempty"`
	CreatedAt    time.Time          `json:"createdAt"`
	ID           string             `json:"id"`

	// Which key matched the worker and at what confidence — provenance
	// the strength function and the unclear queue both read (§4.1).
	Matched *ClaimMatched `json:"matched,omitempty"`
	PartyID string        `json:"partyId"`

	// Portion of the unit attributed to this party. Absent means the whole
	// of it.
	Share *float64 `json:"share,omitempty"`

	// ACCEPTED is reachable by confirm, auto-confirm or
	// supervisor-assisted, and all three release payment (W4). DISPUTED
	// may follow ACCEPTED — silence is not consent against the worker
	// (W3).
	State  ClaimState `json:"state"`
	UnitID string     `json:"unitId"`
}

type ClaimConfirmation struct {
	At             *time.Time              `json:"at,omitempty"`
	NotifiedAt     *time.Time              `json:"notifiedAt,omitempty"`
	Route          *ClaimConfirmationRoute `json:"route,omitempty"`
	WindowClosesAt time.Time               `json:"windowClosesAt"`
	WindowOpenedAt time.Time               `json:"windowOpenedAt"`
}

type ClaimConfirmationRoute string

const (
	ClaimConfirmationRouteSelf     ClaimConfirmationRoute = "self"
	ClaimConfirmationRouteAuto     ClaimConfirmationRoute = "auto"
	ClaimConfirmationRouteAssisted ClaimConfirmationRoute = "assisted"
)

// Which key matched the worker and at what confidence — provenance the
// strength function and the unclear queue both read (§4.1).
type ClaimMatched struct {
	Confidence float64         `json:"confidence"`
	Key        ClaimMatchedKey `json:"key"`
}

type ClaimMatchedKey string

const (
	ClaimMatchedKeyNationalIDHash ClaimMatchedKey = "national-id-hash"
	ClaimMatchedKeyContactRoute   ClaimMatchedKey = "contact-route"
	ClaimMatchedKeyRosterID       ClaimMatchedKey = "roster-id"
)

// ACCEPTED is reachable by confirm, auto-confirm or supervisor-assisted,
// and all three release payment (W4). DISPUTED may follow ACCEPTED —
// silence is not consent against the worker (W3).
type ClaimState string

const (
	ClaimStateDRAFT    ClaimState = "DRAFT"
	ClaimStateNOTIFIED ClaimState = "NOTIFIED"
	ClaimStateACCEPTED ClaimState = "ACCEPTED"
	ClaimStateDISPUTED ClaimState = "DISPUTED"
)

// What was actually paid, keyed to a Unit by event_id. Reconciliation
// compares instructed against confirmed and gives every gap one reason and
// one owner (§10, W10).
type CompensationLinkedRecordPayload struct {
	AmountMinor   int                                           `json:"amountMinor"`
	ConfirmedAt   *time.Time                                    `json:"confirmedAt,omitempty"`
	Currency      string                                        `json:"currency"`
	EventID       string                                        `json:"eventId"`
	FailureReason *CompensationLinkedRecordPayloadFailureReason `json:"failureReason,omitempty"`
	InstructionID string                                        `json:"instructionId"`
	RailRef       *string                                       `json:"railRef,omitempty"`
	State         CompensationLinkedRecordPayloadState          `json:"state"`
}

type CompensationLinkedRecordPayloadFailureReason struct {
	Code         string `json:"code"`
	Explanation  string `json:"explanation"`
	OwnerPartyID string `json:"ownerPartyId"`
}

type CompensationLinkedRecordPayloadState string

const (
	CompensationLinkedRecordPayloadStateSENT      CompensationLinkedRecordPayloadState = "SENT"
	CompensationLinkedRecordPayloadStateCONFIRMED CompensationLinkedRecordPayloadState = "CONFIRMED"
	CompensationLinkedRecordPayloadStateFAILED    CompensationLinkedRecordPayloadState = "FAILED"
)

// One of the three consent moments occurred, with scope (§9). The three
// are distinct objects, never collapsed.
type Consent struct {

	// Object-store key for a voice recording or signed form. The artefact
	// itself never lives in the database.
	ArtefactRef *string `json:"artefactRef,omitempty"`

	// Voice recording is a valid capture for non-literate workers (§9).
	CaptureMethod ConsentCaptureMethod `json:"captureMethod"`
	CapturedAt    time.Time            `json:"capturedAt"`
	ID            string               `json:"id"`

	// enrolment: the right to fetch and hold evidence.
	// issuance-confirmation: is the draft record true. disclosure: who may
	// see what, per presentation.
	Moment    ConsentMoment `json:"moment"`
	RevokedAt *time.Time    `json:"revokedAt,omitempty"`

	// What was consented to. For disclosure this names who asked and why
	// — showing the bare QR is itself consent for the non-identifying
	// payload, anything more is explicit and recorded.
	Scope          ConsentScope `json:"scope"`
	SubjectPartyID string       `json:"subjectPartyId"`
}

// Voice recording is a valid capture for non-literate workers (§9).
type ConsentCaptureMethod string

const (
	ConsentCaptureMethodScreen   ConsentCaptureMethod = "screen"
	ConsentCaptureMethodSMS      ConsentCaptureMethod = "sms"
	ConsentCaptureMethodUSSD     ConsentCaptureMethod = "ussd"
	ConsentCaptureMethodVoice    ConsentCaptureMethod = "voice"
	ConsentCaptureMethodAssisted ConsentCaptureMethod = "assisted"
)

// enrolment: the right to fetch and hold evidence. issuance-confirmation:
// is the draft record true. disclosure: who may see what, per
// presentation.
type ConsentMoment string

const (
	ConsentMomentEnrolment            ConsentMoment = "enrolment"
	ConsentMomentIssuanceConfirmation ConsentMoment = "issuance-confirmation"
	ConsentMomentDisclosure           ConsentMoment = "disclosure"
)

// What was consented to. For disclosure this names who asked and why —
// showing the bare QR is itself consent for the non-identifying payload,
// anything more is explicit and recorded.
type ConsentScope struct {
	Fields             []string `json:"fields,omitempty"`
	Purpose            string   `json:"purpose"`
	RequestedByPartyID *string  `json:"requestedByPartyId,omitempty"`
	TargetID           *string  `json:"targetId,omitempty"`
}

// A challenge to a Claim, Credential or LinkedRecord exists, and where it
// stands. It never touches the Unit: the record that work happened
// survives every dispute about who did it (W5).
type Contest struct {
	ID              string        `json:"id"`
	RaisedAt        time.Time     `json:"raisedAt"`
	RaisedByPartyID string        `json:"raisedByPartyId"`
	Reason          string        `json:"reason"`
	Resolution      *string       `json:"resolution,omitempty"`
	ResolvedAt      *time.Time    `json:"resolvedAt,omitempty"`
	State           ContestState  `json:"state"`
	Target          ContestTarget `json:"target"`
}

type ContestState string

const (
	ContestStateOPEN      ContestState = "OPEN"
	ContestStateUPHELD    ContestState = "UPHELD"
	ContestStateREJECTED  ContestState = "REJECTED"
	ContestStateWITHDRAWN ContestState = "WITHDRAWN"
)

type ContestTarget struct {
	ID string `json:"id"`

	// Deliberately not 'unit'. A Contest against a Unit is not
	// expressible, which is how W5 is enforced by shape rather than by
	// review.
	Kind ContestTargetKind `json:"kind"`
}

// Deliberately not 'unit'. A Contest against a Unit is not expressible,
// which is how W5 is enforced by shape rather than by review.
type ContestTargetKind string

const (
	ContestTargetKindClaim        ContestTargetKind = "claim"
	ContestTargetKindCredential   ContestTargetKind = "credential"
	ContestTargetKindLinkedRecord ContestTargetKind = "linked-record"
)

// A bounded operational scope with its own configuration and activation
// gates. 'Project' and 'campaign' are what profiles call it; a training
// cohort is one too.
type Context struct {
	ActivationGates []ContextActivationGatesItem `json:"activationGates,omitempty"`

	// L2 data. The core stores and returns it and never reads inside it.
	Configuration map[string]any `json:"configuration,omitempty"`
	ID            string         `json:"id"`

	// Profile vocabulary: project, campaign, cohort. The core does not
	// interpret it.
	Kind         string       `json:"kind"`
	Name         string       `json:"name"`
	OwnerPartyID string       `json:"ownerPartyId"`
	ParentID     *string      `json:"parentId,omitempty"`
	Period       Period       `json:"period"`
	State        ContextState `json:"state"`
}

type ContextActivationGatesItem struct {
	Name        string     `json:"name"`
	SatisfiedAt *time.Time `json:"satisfiedAt,omitempty"`
}

type ContextState string

const (
	ContextStateDRAFT  ContextState = "DRAFT"
	ContextStateACTIVE ContextState = "ACTIVE"
	ContextStateCLOSED ContextState = "CLOSED"
)

// A signed, holder-owned projection of an accepted Claim (§5). This
// record is CREST's own bookkeeping, not the credential: there is
// deliberately no credential register (§3), the worker's wallet holds the
// only complete copy, and the status list is the single central fact.
type Credential struct {
	ClaimID    string       `json:"claimId"`
	Definition VersionedRef `json:"definition"`

	// Of the issued credential document, so a presented credential can be
	// tied to this record without storing the document.
	Digest   string           `json:"digest"`
	Format   CredentialFormat `json:"format"`
	ID       string           `json:"id"`
	IssuedAt time.Time        `json:"issuedAt"`
	Issuer   string           `json:"issuer"`

	// Carried onto the credential so a verifier can derive the tier
	// without reaching back into CREST. Facts, never the tier itself
	// (§6).
	Provenance Provenance `json:"provenance"`

	// One bit meaning 'still stands', carrying nothing else. Unlinkable
	// bulk data by design (§9).
	StatusListEntry CredentialStatusListEntry `json:"statusListEntry"`

	// The pairwise subject the credential is about. Never a national
	// identifier (W9).
	SubjectRef string `json:"subjectRef"`
}

type CredentialFormat string

const (
	CredentialFormatJsonldEd25519 CredentialFormat = "jsonld-ed25519"
	CredentialFormatSdJwt         CredentialFormat = "sd-jwt"
)

// One bit meaning 'still stands', carrying nothing else. Unlinkable bulk
// data by design (§9).
type CredentialStatusListEntry struct {
	Index   int    `json:"index"`
	ListURL string `json:"listUrl"`
}

// What counts as a completed instance of an activity, what evidence proves
// it at which strength, who may attest. Versioned, immutable once ACTIVE,
// three faces of one signed record (§7).
type Definition struct {
	ActivatedAt       *time.Time         `json:"activatedAt,omitempty"`
	Activity          DefinitionActivity `json:"activity"`
	AuthoredByPartyID string             `json:"authoredByPartyId"`

	// An Authorization must carry one of these functions to submit
	// evidence against this definition.
	AuthorisedAttesterFunctions []string  `json:"authorisedAttesterFunctions"`
	CreatedAt                   time.Time `json:"createdAt"`

	// Three projections of one record, never three documents (§7).
	Faces DefinitionFaces `json:"faces"`
	ID    string          `json:"id"`

	// The unit a Unit's outcome is counted in. Comes from here, never from
	// a source system.
	OutcomeUnit string `json:"outcomeUnit"`

	// Must differ from authoredByPartyId. Separation of duties is an L1
	// rule enforced in the definitions service, not left to product UI
	// (§7).
	RatifiedByPartyID *string         `json:"ratifiedByPartyId,omitempty"`
	State             DefinitionState `json:"state"`
	SupersededBy      *VersionedRef   `json:"supersededBy,omitempty"`

	// L2 data read by the L1 strength function (§6). Rules are evaluated
	// in order; the first whose conditions all hold gives the tier. The
	// function is identical everywhere; this table is not.
	TierMap []DefinitionTierMapItem `json:"tierMap"`
	Version int                     `json:"version"`
}

type DefinitionActivity struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

// Three projections of one record, never three documents (§7).
type DefinitionFaces struct {
	Platform DefinitionFacesPlatform `json:"platform"`
	Verifier DefinitionFacesVerifier `json:"verifier"`
	Worker   DefinitionFacesWorker   `json:"worker"`
}

type DefinitionFacesPlatform struct {
	RequiredFields []string `json:"requiredFields"`
	SchemaRef      string   `json:"schemaRef"`
	SourceSystems  []string `json:"sourceSystems"`
}

type DefinitionFacesVerifier struct {
	AuthorisedIssuers []string  `json:"authorisedIssuers"`
	SpecifiedAt       time.Time `json:"specifiedAt"`
	SpecifierPartyID  string    `json:"specifierPartyId"`
}

type DefinitionFacesWorker struct {
	EvidenceInPlainLanguage []string `json:"evidenceInPlainLanguage"`
	Summary                 string   `json:"summary"`
	TierCeiling             int      `json:"tierCeiling"`
}

type DefinitionState string

const (
	DefinitionStateDRAFT      DefinitionState = "DRAFT"
	DefinitionStateRATIFIED   DefinitionState = "RATIFIED"
	DefinitionStateACTIVE     DefinitionState = "ACTIVE"
	DefinitionStateSUPERSEDED DefinitionState = "SUPERSEDED"
)

type DefinitionTierMapItem struct {
	CaptureMethodIn      []CaptureMethod    `json:"captureMethodIn"`
	MinIdentityAssurance *IdentityAssurance `json:"minIdentityAssurance,omitempty"`
	RequiresFields       []string           `json:"requiresFields,omitempty"`
	SourceClassIn        []SourceClass      `json:"sourceClassIn"`
	Tier                 int                `json:"tier"`
}

// Derived from a Party's identity bindings, never asserted (§4.1).
// Present in a computed view; never a stored field on Party.
type IdentityAssurance string

const (
	IdentityAssuranceIA0 IdentityAssurance = "IA-0"
	IdentityAssuranceIA1 IdentityAssurance = "IA-1"
	IdentityAssuranceIA2 IdentityAssurance = "IA-2"
	IdentityAssuranceIA3 IdentityAssurance = "IA-3"
)

// A typed, versioned attachment keyed to a Unit, Claim or Definition by
// identifier — carrying its own lifecycle so the core object is never
// hostage to it. The extension point: compensation, obligations,
// endorsements and scores all live here, never in the core.
type LinkedRecord struct {
	CreatedAt time.Time           `json:"createdAt"`
	ID        string              `json:"id"`
	KeyedTo   LinkedRecordKeyedTo `json:"keyedTo"`

	// Shape is the profile's business. Validated against the profile's own
	// schema by whatever service owns that profile.
	Payload map[string]any `json:"payload"`

	// The record's own lifecycle, independent of the object it is keyed
	// to.
	State string `json:"state"`

	// Defined by a profile, never by the core. The core stores the payload
	// opaquely.
	Type    string `json:"type"`
	Version int    `json:"version"`
}

type LinkedRecordKeyedTo struct {
	ID   string                  `json:"id"`
	Kind LinkedRecordKeyedToKind `json:"kind"`
}

type LinkedRecordKeyedToKind string

const (
	LinkedRecordKeyedToKindUnit       LinkedRecordKeyedToKind = "unit"
	LinkedRecordKeyedToKindClaim      LinkedRecordKeyedToKind = "claim"
	LinkedRecordKeyedToKindDefinition LinkedRecordKeyedToKind = "definition"
)

// A quantity of a defined activity. The unit comes from the definition,
// never from the source system.
type Outcome struct {
	Unit  string  `json:"unit"`
	Value float64 `json:"value"`
}

// An actor exists — person or organisation. Persons need only a name and
// one contact route; identity binds late (§4). 'Worker' is a role a Party
// holds, not a type.
type Party struct {

	// At least one, because W2 is unenforceable against a Party nobody can
	// reach.
	ContactRoutes []PartyContactRoutesItem `json:"contactRoutes"`
	CreatedAt     time.Time                `json:"createdAt"`
	DisplayName   string                   `json:"displayName"`
	ID            string                   `json:"id"`

	// Append-only. Re-binding adds a record; history is never rewritten
	// (§4.1). The assurance level is derived from these, never stored.
	IdentityBindings []PartyIdentityBindingsItem `json:"identityBindings,omitempty"`
	Kind             PartyKind                   `json:"kind"`
}

type PartyContactRoutesItem struct {
	Kind       PartyContactRoutesItemKind `json:"kind"`
	Value      string                     `json:"value"`
	VerifiedAt *time.Time                 `json:"verifiedAt,omitempty"`
}

type PartyContactRoutesItemKind string

const (
	PartyContactRoutesItemKindPhone      PartyContactRoutesItemKind = "phone"
	PartyContactRoutesItemKindEmail      PartyContactRoutesItemKind = "email"
	PartyContactRoutesItemKindUSSD       PartyContactRoutesItemKind = "ussd"
	PartyContactRoutesItemKindSupervisor PartyContactRoutesItemKind = "supervisor"
)

type PartyIdentityBindingsItem struct {
	AssertedAt time.Time  `json:"assertedAt"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`

	// For matching only. A salted hash and the salt's identifier — never
	// the identifier itself, and never for fixtures either (W9).
	NationalIDHash *PartyIdentityBindingsItemNationalIDHash `json:"nationalIdHash,omitempty"`
	Provider       string                                   `json:"provider"`
	ProviderClass  PartyIdentityBindingsItemProviderClass   `json:"providerClass"`

	// The provider's pairwise subject identifier. With eSignet this
	// partitions by relying party, not by client (finding E6).
	SubjectRef string `json:"subjectRef"`
}

// For matching only. A salted hash and the salt's identifier — never the
// identifier itself, and never for fixtures either (W9).
type PartyIdentityBindingsItemNationalIDHash struct {
	Alg     PartyIdentityBindingsItemNationalIDHashAlg `json:"alg"`
	SaltRef string                                     `json:"saltRef"`
	Value   string                                     `json:"value"`
}

type PartyIdentityBindingsItemNationalIDHashAlg string

const (
	PartyIdentityBindingsItemNationalIDHashAlgSha256 PartyIdentityBindingsItemNationalIDHashAlg = "sha256"
)

type PartyIdentityBindingsItemProviderClass string

const (
	PartyIdentityBindingsItemProviderClassEsignet      PartyIdentityBindingsItemProviderClass = "esignet"
	PartyIdentityBindingsItemProviderClassMosipIda     PartyIdentityBindingsItemProviderClass = "mosip-ida"
	PartyIdentityBindingsItemProviderClassGenericOidc  PartyIdentityBindingsItemProviderClass = "generic-oidc"
	PartyIdentityBindingsItemProviderClassMobileOtp    PartyIdentityBindingsItemProviderClass = "mobile-otp"
	PartyIdentityBindingsItemProviderClassDocumentSeen PartyIdentityBindingsItemProviderClass = "document-seen"
	PartyIdentityBindingsItemProviderClassAsserted     PartyIdentityBindingsItemProviderClass = "asserted"
)

type PartyKind string

const (
	PartyKindPerson       PartyKind = "person"
	PartyKindOrganisation PartyKind = "organisation"
)

// What should be paid, keyed to a Unit by event_id only — never inside
// the credential (§8). Released on every T=7 exit, including dispute: a
// dispute contests the record, it does not withhold the money (W4).
type PaymentInstructionLinkedRecordPayload struct {
	AmountMinor int    `json:"amountMinor"`
	ClaimID     string `json:"claimId"`
	Currency    string `json:"currency"`
	EventID     string `json:"eventId"`

	// Every held payment has a reason with an owner (W10). Absent unless
	// state is HELD.
	HeldReason   *PaymentInstructionLinkedRecordPayloadHeldReason `json:"heldReason,omitempty"`
	PayeePartyID string                                           `json:"payeePartyId"`
	ReleasedAt   time.Time                                        `json:"releasedAt"`

	// Which of the four exits released it. All four are here on purpose
	// — an instruction with no 'dispute' case is a system that quietly
	// withholds pay.
	ReleasedBy PaymentInstructionLinkedRecordPayloadReleasedBy `json:"releasedBy"`
}

// Every held payment has a reason with an owner (W10). Absent unless state
// is HELD.
type PaymentInstructionLinkedRecordPayloadHeldReason struct {
	Code         string `json:"code"`
	Explanation  string `json:"explanation"`
	OwnerPartyID string `json:"ownerPartyId"`
}

// Which of the four exits released it. All four are here on purpose — an
// instruction with no 'dispute' case is a system that quietly withholds
// pay.
type PaymentInstructionLinkedRecordPayloadReleasedBy string

const (
	PaymentInstructionLinkedRecordPayloadReleasedBySelf     PaymentInstructionLinkedRecordPayloadReleasedBy = "self"
	PaymentInstructionLinkedRecordPayloadReleasedByAuto     PaymentInstructionLinkedRecordPayloadReleasedBy = "auto"
	PaymentInstructionLinkedRecordPayloadReleasedByAssisted PaymentInstructionLinkedRecordPayloadReleasedBy = "assisted"
	PaymentInstructionLinkedRecordPayloadReleasedByDispute  PaymentInstructionLinkedRecordPayloadReleasedBy = "dispute"
)

// The rate, keyed to a Definition. Linked by reference, never embedded: a
// definition is complete and usable with no rate attached, because
// recognition is a use of its own (§7).
type PaymentSetupLinkedRecordPayload struct {
	EffectiveFrom      time.Time                                         `json:"effectiveFrom"`
	PayerPartyID       string                                            `json:"payerPartyId"`
	RatePerOutcomeUnit PaymentSetupLinkedRecordPayloadRatePerOutcomeUnit `json:"ratePerOutcomeUnit"`
}

type PaymentSetupLinkedRecordPayloadRatePerOutcomeUnit struct {

	// Minor units. Money is never a float.
	AmountMinor int    `json:"amountMinor"`
	Currency    string `json:"currency"`
}

type Period struct {
	End   *time.Time `json:"end,omitempty"`
	Start time.Time  `json:"start"`
}

// Attached by the adapter and validated by the pipeline. Whatever the
// source asserts about its own trustworthiness is ignored (§8). These are
// the facts the strength function reads; the tier itself is never stored
// (§6).
type Provenance struct {

	// Which adapter version translated the record. Resolvable in the
	// adapter registry, so a verifier can walk evidence back to a known
	// translator.
	AdapterRef     string         `json:"adapterRef"`
	CaptureMethod  CaptureMethod  `json:"captureMethod"`
	ReceivedAt     time.Time      `json:"receivedAt"`
	SourceClass    SourceClass    `json:"sourceClass"`
	SourceExposure SourceExposure `json:"sourceExposure"`

	// The source system's own identifier for the record. Opaque to CREST.
	SourceRecordRef *string `json:"sourceRecordRef,omitempty"`
}

// What kind of system the record came from. Adapter-attached, never
// source-asserted (§8).
type SourceClass string

const (
	SourceClassNationalSystem      SourceClass = "national-system"
	SourceClassInstitutionalSystem SourceClass = "institutional-system"
	SourceClassProgrammeSystem     SourceClass = "programme-system"
	SourceClassSupervisedCapture   SourceClass = "supervised-capture"
	SourceClassSelfReported        SourceClass = "self-reported"
)

// The transport a record arrived by. Recorded, and deliberately not an
// input to strength (§8) — an attester who could raise a tier by
// choosing how to send the file would have found a way to assert strength.
type SourceExposure string

const (
	SourceExposurePushAPI          SourceExposure = "push-api"
	SourceExposureConsentPull      SourceExposure = "consent-pull"
	SourceExposureSignedBatch      SourceExposure = "signed-batch"
	SourceExposureSupervisedUpload SourceExposure = "supervised-upload"
)

// A published, versioned permission set a Party may qualify under.
// Domain-neutral: the permission names come from profiles.
type Terms struct {
	ID   string `json:"id"`
	Name string `json:"name"`

	// Opaque strings. The core never interprets them; profiles and
	// definitions do.
	Permissions []string      `json:"permissions"`
	PublishedAt time.Time     `json:"publishedAt"`
	Supersedes  *VersionedRef `json:"supersedes,omitempty"`
	Version     int           `json:"version"`
}

// L2-adjacent specification (§2.1): it names roles and LinkedRecord types
// and touches no core schema. The test of the object model is that a
// second profile needs nothing new.
type TrustedPaymentsProfile struct {
	LinkedRecordTypes []string `json:"linkedRecordTypes"`

	// Roles a Party holds in this profile. 'Worker' is here, not in the
	// Party primitive.
	Roles TrustedPaymentsProfileRoles `json:"roles"`
}

// Roles a Party holds in this profile. 'Worker' is here, not in the Party
// primitive.
type TrustedPaymentsProfileRoles struct {
	Attester  string `json:"attester"`
	Payer     string `json:"payer"`
	Specifier string `json:"specifier"`
	Subject   string `json:"subject"`
}

// An instance of a defined activity happened — independent of who did
// it. A disputed Claim never destroys the Unit (W5).
type Unit struct {
	ContextID  string       `json:"contextId"`
	CreatedAt  time.Time    `json:"createdAt"`
	Definition VersionedRef `json:"definition"`

	// Optional source fields, kept verbatim. Read by the tier map's
	// requiresFields; never interpreted by the core.
	Enrichment map[string]any `json:"enrichment,omitempty"`

	// Coarse only. Raw location is never stored (§8).
	Geography  *string    `json:"geography,omitempty"`
	ID         string     `json:"id"`
	Outcome    Outcome    `json:"outcome"`
	Period     Period     `json:"period"`
	Provenance Provenance `json:"provenance"`
}

// Everything references by versioned identifier (§2). A bare id is a
// reference that changes meaning underneath the thing holding it.
type VersionedRef struct {
	ID      string `json:"id"`
	Version int    `json:"version"`
}

// The credential a worker holds (§5). It carries provenance facts and
// never a tier: the tier is computed at presentation time against the
// pinned definition version, so re-assessing a compromised source
// downgrades every affected credential instantly without reissuance (§6).
type WorkEventCredential struct {

	// W3C VC context plus CREST's own.
	Context           []string                             `json:"@context"`
	CredentialStatus  WorkEventCredentialCredentialStatus  `json:"credentialStatus"`
	CredentialSubject WorkEventCredentialCredentialSubject `json:"credentialSubject"`
	ID                string                               `json:"id"`
	Issuer            string                               `json:"issuer"`
	Proof             *WorkEventCredentialProof            `json:"proof,omitempty"`

	// ['VerifiableCredential', 'WorkEventCredential']
	Type      []string  `json:"type"`
	ValidFrom time.Time `json:"validFrom"`
}

type WorkEventCredentialCredentialStatus struct {
	ID                   string `json:"id"`
	StatusListCredential string `json:"statusListCredential"`
	StatusListIndex      string `json:"statusListIndex"`
	StatusPurpose        string `json:"statusPurpose"`
	Type                 string `json:"type"`
}

type WorkEventCredentialCredentialSubject struct {

	// Which route accepted the claim. A verifier can see that a credential
	// was auto-confirmed rather than actively confirmed, and weigh it.
	Confirmation WorkEventCredentialCredentialSubjectConfirmation `json:"confirmation"`

	// The pairwise subject reference. Never a national identifier, and
	// never a name (W8, W9).
	ID string `json:"id"`

	// The facts the strength function reads. A credential that stated its
	// own tier would freeze a judgement verifiers must be free to make
	// differently.
	Provenance Provenance                                    `json:"provenance"`
	WorkEvent  WorkEventCredentialCredentialSubjectWorkEvent `json:"workEvent"`
}

// Which route accepted the claim. A verifier can see that a credential was
// auto-confirmed rather than actively confirmed, and weigh it.
type WorkEventCredentialCredentialSubjectConfirmation struct {
	At    time.Time                                             `json:"at"`
	Route WorkEventCredentialCredentialSubjectConfirmationRoute `json:"route"`
}

type WorkEventCredentialCredentialSubjectConfirmationRoute string

const (
	WorkEventCredentialCredentialSubjectConfirmationRouteSelf     WorkEventCredentialCredentialSubjectConfirmationRoute = "self"
	WorkEventCredentialCredentialSubjectConfirmationRouteAuto     WorkEventCredentialCredentialSubjectConfirmationRoute = "auto"
	WorkEventCredentialCredentialSubjectConfirmationRouteAssisted WorkEventCredentialCredentialSubjectConfirmationRoute = "assisted"
)

type WorkEventCredentialCredentialSubjectWorkEvent struct {
	Activity   string       `json:"activity"`
	Definition VersionedRef `json:"definition"`
	EventID    string       `json:"eventId"`

	// The names of the fields the source record carried — names only,
	// never values. A definition's tier map can require a field, and a
	// verifier who cannot tell whether the record had it resolves a lower
	// tier than the issuer did. Offline is the case that matters (W6), so
	// the credential has to carry enough to answer the question, and a
	// list of field names discloses nothing about the household they
	// describe.
	EvidenceFields []string `json:"evidenceFields,omitempty"`
	Geography      *string  `json:"geography,omitempty"`
	Outcome        Outcome  `json:"outcome"`
	Period         Period   `json:"period"`
}

type WorkEventCredentialProof struct {
	Created time.Time `json:"created"`

	// Ed25519 over JCS-canonicalised JSON. Chosen over the JSON-LD suite
	// because verifying that one requires resolving a context document,
	// and a verifier that must fetch a URL is not offline (W6).
	Cryptosuite        string `json:"cryptosuite"`
	ProofPurpose       string `json:"proofPurpose"`
	ProofValue         string `json:"proofValue"`
	Type               string `json:"type"`
	VerificationMethod string `json:"verificationMethod"`
}
